name: Kiffy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dartlin: ^0.6.3
  image: ^4.1.3

  #firebase
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_crashlytics: ^3.3.7

  #UI Component
  gradient_borders: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.1.1+1
  flutter_card_swiper: ^5.0.0
  image_picker: ^0.8.6
  drop_shadow_image: ^0.9.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0

  #state
  flutter_riverpod: ^2.4.3

  http: ^0.13.5
  go_router: ^6.5.6
  easy_localization: ^3.0.1
  geolocator: ^9.0.2
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  flutter_flavor: ^3.1.3
  google_sign_in: ^6.1.0

  collection: ^1.17.2

  dio: "^5.0.0"
  openapi:
    git:
      url: git@github.com:kiiffy/idl.git
      path: openapi/gen/api/dart-dio
      ref: 8fbd43462ea98f39ed462db4709cc68631819748

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  androud: true
  ios: true
  image_path: "assets/icons/kiffy_logo_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
