// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    appGroupId: "club.kiffy.app.dev",
    apiKey: 'AIzaSyDk928u7VAhZY0ZQI3szn-9zV-nHsVMPAg',
    appId: '1:788804351569:android:032ff1b0b1c240b110ea70',
    messagingSenderId: '788804351569',
    projectId: 'kiffy-cbf6d',
    storageBucket: 'kiffy-cbf6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    // TODO 바꾸어주어야함
    apiKey: 'AIzaSyAfVI8Fd-W9jD8JqrNbsw50CGg1Up2gUK0',
    appId: '1:858024060821:ios:195534625f08d176edb89c',
    messagingSenderId: '858024060821',
    projectId: 'kiffy-dev-cbc76',
    storageBucket: 'kiffy-dev-cbc76.appspot.com',
    iosClientId:
        '858024060821-dsflvrrjr4fh6p2qv5u4du4s6b11edq6.apps.googleusercontent.com',
    iosBundleId: 'club.kiffy.app',
  );
}
